### PR TITLE
just added your uglify test

### PR DESCRIPTION
**Pull request by boussou**
Added the uglify test you mentioned on the README.
(I also added a quick command to rank the files size)

### CODE REVIEW

**Comment by boussou** [comment]
Added Closure just to cross check

Thanks, you convinced me about **rollup**.

**Comment by nolanlawson** [comment]
Hi, thanks for the contribution, but I'd kind of rather keep this repo small and focused on comparing Rollup to Webpack and Browserify. I think your research is really interesting, though, and would encourage that you fork and publish those results somewhere! :)

BTW in case it makes things a bit easier, there is this project which automatically downloads the Closure JAR, sets up Java, etc: https://www.npmjs.com/package/closurecompiler

**Comment by boussou** [comment]
thanks for the hint regarding Closure . ;-)

**Comment by boussou** [comment]
**Just for the record.**

> **Deprecation notice:** This project is outdated. Alternatives:
> - [closure-compiler](https://www.npmjs.com/package/closure-compiler)
> - [google-closure-compiler](https://www.npmjs.com/package/google-closure-compiler)
> - [closure-builder](https://www.npmjs.com/package/closure-builder)

(from project page https://github.com/dcodeIO/ClosureCompiler.js)

**Comment by boussou** [comment]
I thnik Closure & Rollup can be a good combination. 
I will try on a real project.

**Comment by nolanlawson** [comment]
Fhanks for the tip! For the purposes of this article, Closure produced output essentially equivalent to Rollup (after Uglification), so I think it's okay to use the old one. But I'll use the new ones from now on!

**Pull request closed without merging**
